[global]
  server role = standalone server
  map to guest = never
  security = user
  log file = /dev/stdout
  max log size = 0
  load printers = no
  disable spoolss = yes

[share]
  path = /srv/share
  browseable = yes
  read only = no
  guest ok = no
  valid users = demo
  force user = demo
